print("Well we")
print("just use more lines")
print("of code")
print("That was easy")
print("Hi Ize Dobbie")
print("Hello Scallie!")
print()
print("We are both Dogs  🐩")
print("oh yes!")
print("This is just a test")
print("edit in Git Hub")
print("edit on the web")