print ("Welcome to your adventure simulator. I am going to ask you a bunch of questions and then create an epic story with you as the star!")
print()

name = input("What is your name?: ")
enemy = input("What is your worst enemy’s name?: ")
superPower = input("What is your superpower?: ")
live = input("Where do you live?: ")
food = input("What is your favorite food?: ")
print()
print("Hello", name+"! Your ability to", superPower, "will make sure you never have to look at", enemy+"’s", name, "again. Go eat", food, "as you walk down the streets of", live, "and use", superPower, "for good and not evil!")